### ISSUE TITLE
GetAllDevices error

### ISSUE THREAD

**Issue by KalKal1976** [jhoralek/pyinels#27]
Hi, after registration I got this error.
It looks as any problem with parsing devices.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/inels/__init__.py", line 48, in async_setup_entry
    hass.data[DOMAIN][DOMAIN_DATA] = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 104, in getAllDevices
    room_devices = self.getRoomDevices(room)
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 95, in getRoomDevices
    return self.__roomDevicesToJson(room_name)
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 203, in __roomDevicesToJson
    device.get_value()
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/resources.py", line 138, in get_value
    raise ex
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/resources.py", line 129, in get_value
    raw = self.__api.read([self.id])
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 157, in read
    return self.__readDeviceData(device_ids)
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 253, in __readDeviceData
    return self.proxy.read(device_ids)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 8002: 'error'>

**Comment by jhoralek** [comment]
You're right. It seems like a parsing problem inside of the pyInels lib.

Open terminal and install pyinels package with pip.  Then in your favorite text editor like vi, vim or nano  write simple script which will comunicate with connection server and return list of raw data from CU UNIT.

Instalation Python

```
sudo apt-get update
sudo apt-get install python3-pip
pip3 --version

pip3 install pyinels
```

Script

```
from pyinels.api import Api
from unittest import TestCase

api = Api("http://IP_ADDRESS_OF_CONNECTION_SERVER", 8001, "CU3")
rooms = api.getRooms()

with open('raw_data.txt', 'w',encoding='utf-8') as f:
    for room in rooms:
        devices = api.getRoomDevicesRaw(room)
        f.write(devices)
        f.write('\n')    
```

save file as devices.py

RUN script

```
python devices.py
```

Send me the result and I'll check it agains my testing tools.

Kind regards!

**Comment by jhoralek** [comment]
Probably exception rise when unknown device is trying to reach data from UNIT. 
Library does not know what kind of command from API to use when reaching data.

Solving with temporary filtering of all unknow devices.  #28

Future solution
----------------
Recognize all unknown device and match right API command to reach data from UNIT.
